//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public Nullable<int> IsActive { get; set; }
        public string Name { get; set; }
        public string ApplicationKey { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> DefaultTimeoutLength { get; set; }
    }
}
