//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentinel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<int> IsVerified { get; set; }
        public Nullable<int> Islocked { get; set; }
        public Nullable<int> IsLoggedIn { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Token { get; set; }
        public string SecurityPhrase { get; set; }
        public string SecurityImage { get; set; }
    }
}
